<?php
/**
 * Template for Mage_Page_Block_Html
 */
$lang=$this->getLang();
$store = Mage::app()->getStore();
$name = $store->getFrontendName();
$randomClass = 'five'.rand(0,5).' ten'.rand(0,10);
$storeId = $store->getStoreId();
$storeCode = $store->getCode();
$theme = $this->helper('wsu_themecontrol');
$template = $this->helper('wsu_themecontrol/template');
$binderClassStr = $theme->getBinderClassStr($storeCode);
$binderStyleStr =  $theme->getBinderStyleStr($storeCode);
$bodyClasses = $storeCode.$storeId.' '.$this->getBodyClass() .' '. $theme->getThemeBodyClasses() .' '. $randomClass;
$spine_tool_bar_color = $theme->getCfgDesign('spine/spine_tool_bar_color');
$show_headerstorename	= $theme->getCfgLayout('spine/show_headerstorename');
$mainContentClasses= $template->getBlockClasses("main_content"); 

?>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js no-svg lt-ie9 lt-ie8 lt-ie7" lang="<?=$lang ?>"> <![endif]-->
<!--[if IE 7]><html class="no-js no-svg lt-ie9 lt-ie8" lang="<?=$lang ?>"> <![endif]-->
<!--[if IE 8]><html class="no-js no-svg lt-ie9" lang="<?=$lang ?>"> <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="<?=$lang ?>"><!--<![endif]-->
<head>
	<?=$this->getChildHtml('head')?>
</head>
<body class=" <?=$bodyClasses?>">
    <!-- WRAPPING -->
    <div id="jacket">
        <div id="binder" class="<?=$binderClassStr?>" style="<?=$binderStyleStr?>">
            <!-- CONTENT -->
            <main id="page" role="main">
                <section class="row" id="siteID">
                    <div style="float:right;">
                        <div class="quick-access <?=$spine_tool_bar_color; ?>" style="font-size:12px; font-weight:bold;">
                            <?=$this->getChildHtml('topLinks') ?>
                        </div>
                    </div>
                    <article>
                        <h2>WSU Marketplace</h2>
                        <?php if($show_headerstorename==1):?><h1><?=$name?></h1><?php endif; ?>
                        
                    </article>
                </section>
                <!-- Responsive Sections -->
                <section class="row side-right padded content_area">
                    <div class="column one">
                        <article>
                        	<?=$this->getChildHtml('after_body_start') ?>
                            <div id="main" class="<?=$mainContentClasses?>" >
                                <?=$this->getChildHtml('topContainer'); ?>
                                <?=$this->getChildHtml('global_notices') ?>
                                <?=$this->getChildHtml('global_messages') ?>
								<?=$this->getChildHtml('breadcrumbs') ?> 
                                <?=$this->getChildHtml('content') ?>
                            </div><!-- end of main -->   
                        </article>
                    </div><!--/column-->
                    <div class="column two">
                        <aside id="sidebar_area">
                            <section>
                            	<?=$this->getChildHtml('right'); ?>
                            </section>
                        </aside>
                    </div><!--/column-->
                </section>
                <footer class="padded">
					<?=$this->getChildHtml('footer') ?>
                    <?=$this->getAbsoluteFooter() ?>
				</footer>
            </main><!--/#page-->
            <!-- /CONTENT -->
    
            <?=$this->getChildHtml('header') ?>
        </div><!--/cover-->
    </div><!--/jacket-->
    <!-- /WRAPPING -->
    <?=$this->getChildHtml('before_body_end') ?>
</body>
</html>
