<?php
    $store = Mage::app()->getDefaultStoreView();
    // Gets the current store's id
    $this->_storeId = $store->getStoreId();
    ?>


<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>
    			<?php 
                
				$productType=$_product->getTypeID();
				$product=Mage::getModel('catalog/product')->load($_product->getId());
                
				$eventStart = $product->getEventstartdate();
                
                $productUrl = $product->getProductUrl();
                $productUrl = parse_url($productUrl);
                $productUrl = rtrim ( Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB), "/" ).$productUrl["path"];
			?>
        <a href="<?=$productUrl?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" style="color:#ececec;font-size: 2em;margin-right: 1em;max-width: 15em;line-height: 1.3em;">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" style="width: 4.6em;height: 4.6em;float:left;margin-right:5px;background:#ececec;"/>
        <?php echo $this->escapeHtml($_product->getName()) ?>
        </a>
    <?php endforeach; ?>
<?php endif; ?>
