<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" style="color:#ececec;font-size: 2em;margin-right: 1em;max-width: 15em;line-height: 1.3em;">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" style="width: 4.6em;height: 4.6em;float:left;margin-right:5px;background:#ececec;"/>
        <?php echo $this->escapeHtml($_product->getName()) ?>
        </a>
    <?php endforeach; ?>
<?php endif; ?>
