<?php 

$_helper = $this->helper('catalog/output');

$theme = $this->helper('wsu_themecontrol');
$template = $this->helper('wsu_themecontrol/template');


$row_type				= $theme->getCfgLayout('product_view/row_type');
$padding				= $theme->getCfgLayout('product_view/padding');
$padding_flanks			= $theme->getCfgLayout('product_view/padding_flanks');
$padding_ends			= $theme->getCfgLayout('product_view/padding_ends');

?>

<?php
//$_layout =  $this->helper('wsu_themecontrol/layout')->getLayoutOptions($this);
?>



<div class="designer_hr"></div>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<?=''//$this->getChildHtml('onlybreadcrumbs')?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> class="row <?=$row_type?> <?=$padding?>  <?=$padding_flanks?>  <?=$padding_ends?>">
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop column two">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
			<?php if ($_product->isSaleable()):?>
				<?php echo $this->getChildChildHtml('containerPrice', '', true, true) ?>
			<?php endif;?>
			<?php echo $this->getTierPriceHtml() ?>
			<?php 
            $short = $_product->getShortDescription();
            if ($short):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>
			<!--
            <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>

            <?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
			-->
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>



            <?php echo $this->getChildHtml('other');?>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
				<div id="lower_box">
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
				</div>
            <?php endif;?>
<?php 
            $full = $_product->getDescription();
            if ($full && $full != $short):?>
                <?php
                    $description_class="";
                    //$description_class.=$_layout["description_area"]["order"]." ";
                    ?>
                <div class="description <?=$description_class?>">
                    <hr style="height:1px;margin-bottom:0px">
                    <h2 style=" font-size: 1.4em;"><?php echo $this->__('Full Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?></div>
                </div>
            <?php endif;?>
        </div>

        <div class="product-img-box column one">
            <?php echo $this->getChildHtml('media') ?>
        </div>
		
		
		
		

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    
    <?php /*
		//@todo
		Look to the js controller script for the 
		var productAddToCartForm = new VarienForm('product_addtocart_form');
		it shouldbn't be in line.
	*/ ?><script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

    <div class="product-collateral">
            
    
    
    
        <?php echo $this->getChildHtml('info_tabs') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
	
	<?php echo $this->getChildHtml('related_products'); ?>
</div>
