<?php
    $_helper    = $this->helper('catalog/output');
    //$_category  = $this->getCurrentCategory();
	$_category = Mage::registry('current_category');
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" style="width:100%"/></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="cat_list_header_top">
	<?=$this->getChildHtml('breadcrumbs') ?>
	<div class="sort_by">
		<label><?php echo $this->__('Sort By') ?></label>
		<select onchange="setLocation(this.value)">
		<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
			<option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
				<?php echo $this->__($_order) ?>
			</option>
		<?php endforeach; ?>
		</select>
		<?php if($this->getCurrentDirection() == 'desc'): ?>
			<a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?>" class="v-middle" /></a>
		<?php else: ?>
			<a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?>" class="v-middle" /></a>
		<?php endif; ?>
	</div>
	<?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
		<?php echo $_leftContent;   ?>
	<?php endif; ?>

</div>

<?php if($this->getCollection()->getSize()): ?>
<div class="cat_list_header_bottom">
    <div class="filtering_result_labels">
		<span class="match_count"><?=$this->getTotalNum()?> <?=( 1 == $this->getTotalNum() ? $this->__("Match") : $this->__("Matches") )?></span>
		<?php if($this->getLastPageNum()>1): ?>
			<span class="paged_label"><?php echo $this->__('Showing %s through %s', $this->getFirstNum(), $this->getLastNum()) ?></span>
		<?php endif; ?>
		
		<?php if ($_stateContent = $this->getChildHtml('state_renderers')): ?>
			<div class="state_of_the_list"><?php echo $_stateContent;   ?></div>
		<?php endif; ?>	
    </div>
	<div class="limiter">
		<?php echo $this->getPagerHtml() ?>
		<div class="viewing_selector">
		<?php echo $this->__('View') ?>
		<?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
			<a href="<?php echo $this->getLimitUrl($_key) ?>" onclick="setLocation(<?php echo $this->getLimitUrl($_key) ?>)"<?php if($this->isLimitCurrent($_key)): ?>class="active"<?php endif ?>>
				<?php echo $_limit ?>
			</a>
		<?php endforeach; ?>
		</div>
	</div>
	<?php if( $this->isExpanded() ): ?>
	<div class="sorter">
		<?php if( $this->isEnabledViewSwitcher() ): ?>
		<!--<p class="view-mode">
			<?php $_modes = $this->getModes(); ?>
			<?php if($_modes && count($_modes)>1): ?>
			<label><?php echo $this->__('as') ?>:</label>
			<?php foreach ($this->getModes() as $_code=>$_label): ?>
				<?php if($this->isModeActive($_code)): ?>
					<strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
				<?php else: ?>
					<a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
				<?php endif; ?>
			<?php endforeach; ?>
			<?php endif; ?>
		</p>-->
		<?php endif; ?>		
	</div>
	<?php endif; ?>
</div>
<?php endif ?>
