<?php if(Mage::getStoreConfig('wsu_themecontrol_layout/responsive/show_breadcrumbs') && $crumbs && is_array($crumbs)): ?><?php endif; ?>
<div id="onlybreadcrumbs"> 
<?php 
if(!$crumbs || !is_array($crumbs)){
	$crumbs = $this->getAllBreadcrumbs();
}

?>
	<?php if($crumbs && is_array($crumbs)): ?>
	<div class="breadcrumbs">
		<ul xmlns:v="http://rdf.data-vocabulary.org/#">
			<?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
				<li class="<?php echo $_crumbName ?>" typeof="v:Breadcrumb">
				<?php if($_crumbInfo['link']): ?>
					<a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>" rel="v:url" property="v:title"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
				<?php elseif($_crumbInfo['last']): ?>
					<strong rel="v:url" property="v:title"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
				<?php else: ?>
					<?php echo $this->escapeHtml($_crumbInfo['label']) ?>
				<?php endif; ?>
				<?php if(!$_crumbInfo['last']): ?>
					<span>/ </span>
				<?php endif; ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
	<?php endif; ?>
 </div>