<div id="localfooter">
	<section>
        <div>
            <article>
				<!--<?=$this->getChildHtml() ?> 
                <address><?=$this->getCopyright() ?></address>
                <a href="http://web.wsu.edu/">University Web Communications</a>, Washington State University, PO Box 645910, Pullman, WA, 99164-5910 USA 509-335-2700 <a href="mailto:web.support@wsu.edu">Contact Us</a>
				<div id="site-global-footer">
					<ul>

						<li><a href="<?php echo $this->getUrl('locations');?>">WSU Locations</a></li>
					</ul>
				</div>
				-->
				<div style="display:flex; flex-flow:row wrap;">
					<div class="footer-cell"></div>
					<div class="footer-cell">
						<a href="http://www.clc.com/" target="_blank" class="licensed-link">Officially licensed collegiate products</a>
					</div>
					<div class="footer-cell two" style="    max-width: 40%;">
						<span class="alumni-message" style="
    line-height: 1em;
    display: inline-block;
    font-size: 1.2em;
    font-weight: 700;
    text-transform: uppercase;
    text-align: right;
    float: left;
    margin-top: .6em;
">Alumni<br>Save 10%</span>
						<img src="/media/store-media/connections.store.wsu.edu/skin/alumni-cards.png" style="
    display: inline-block;
    vertical-align: bottom;
    width: 27%;
    /* font-size: 0.7em; */
    float: left;
">
						<span style="
    display: inline-block;
    font-size: 0.5em;
    max-width: 46%;
    float: left;
    margin-top: 1.6em;
	    line-height: 0.9em;
"> All card-carrying WSU alumni can save at the Connections Store.  * discount excludes wine, cheese and sale items.</span>
					</div>
					<div class="footer-cell"></div>
				</div>
				
				
				<div id="contact-details" itemscope itemtype="http://schema.org/Organization"> 
					<span itemprop="department"  content="<?=Mage::getStoreConfig('general/store_information/department');?>"></span> 
					<span itemprop="name" content="<?=Mage::getStoreConfig('general/store_information/name');?>"></span> 
					<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
						<span itemprop="location" content="<?=Mage::getStoreConfig('general/store_information/location');?>"></span>
						<span itemprop="streetAddress" content="<?=Mage::getStoreConfig('general/store_information/streetAddress');?>"></span>
						<span itemprop="addressLocality" content="<?=Mage::getStoreConfig('general/store_information/addressLocality');?>"></span>
						<span itemprop="addressRegion" content="<?=Mage::getStoreConfig('general/store_information/addressRegion');?>"></span>
						<span itemprop="postalCode" content="<?=Mage::getStoreConfig('general/store_information/postalCode');?>"></span>
					</div>
					<span itemprop="telephone" content="<?=Mage::getStoreConfig('general/store_information/telephone');?>"></span>
					<span itemprop="email" content="<?=Mage::getStoreConfig('general/store_information/email');?>"></span>
					<span itemprop="contactPoint" content="<?=Mage::getStoreConfig('general/store_information/contactPoint');?>"></span>
					<span itemprop="url" content="<?=Mage::getStoreConfig('general/store_information/url');?>"></span>
				</div>
				
				
            </article>
        </div>
    </section>
</div>