<div id="localfooter">
	<section>
        <div>
            <article>
				<!--<?=$this->getChildHtml() ?> 
                <address><?=$this->getCopyright() ?></address>
                <a href="http://web.wsu.edu/">University Web Communications</a>, Washington State University, PO Box 645910, Pullman, WA, 99164-5910 USA 509-335-2700 <a href="mailto:web.support@wsu.edu">Contact Us</a>
				<div id="site-global-footer">
					<ul>

						<li><a href="<?php echo $this->getUrl('locations');?>">WSU Locations</a></li>
					</ul>
				</div>
				-->
				<div class="footer-area">
					<div class="footer-cell"></div>
					<div class="footer-cell">
						<a href="http://www.clc.com/" target="_blank" class="licensed-link">Officially licensed collegiate products</a>
					</div>
					<div class="footer-cell two alumni">
					<a href="http://alumni.wsu.edu/s/1613/2015/index.aspx?sid=1613&gid=2&pgid=384" target="_blank">
						<span class="message">Alumni<br>Save 10%</span>
						<img src="/media/store-media/connections.store.wsu.edu/skin/alumni-cards.png"/>
						<span class="disclaimer"> All card-carrying WSU alumni can save at the Connections Store.  * discount excludes wine, cheese and sale items.</span>
</a>
					</div>
					<div class="footer-cell"></div>
				</div>
				
				
				<div id="contact-details" itemscope itemtype="http://schema.org/Organization"> 
					<span itemprop="department"  content="<?=Mage::getStoreConfig('general/store_information/department');?>"></span> 
					<span itemprop="name" content="<?=Mage::getStoreConfig('general/store_information/name');?>"></span> 
					<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
						<span itemprop="location" content="<?=Mage::getStoreConfig('general/store_information/location');?>"></span>
						<span itemprop="streetAddress" content="<?=Mage::getStoreConfig('general/store_information/streetAddress');?>"></span>
						<span itemprop="addressLocality" content="<?=Mage::getStoreConfig('general/store_information/addressLocality');?>"></span>
						<span itemprop="addressRegion" content="<?=Mage::getStoreConfig('general/store_information/addressRegion');?>"></span>
						<span itemprop="postalCode" content="<?=Mage::getStoreConfig('general/store_information/postalCode');?>"></span>
					</div>
					<span itemprop="telephone" content="<?=Mage::getStoreConfig('general/store_information/telephone');?>"></span>
					<span itemprop="email" content="<?=Mage::getStoreConfig('general/store_information/email');?>"></span>
					<span itemprop="contactPoint" content="<?=Mage::getStoreConfig('general/store_information/contactPoint');?>"></span>
					<span itemprop="url" content="<?=Mage::getStoreConfig('general/store_information/url');?>"></span>
				</div>
				
				
            </article>
        </div>
    </section>
</div>