<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
 
 $store = Mage::app()->getStore();
 $name = $store->getFrontendName();
 
 $theme = $this->helper('wsu_themecontrol');	
 $headerInnerBgColor	= $theme->getCfgDesign('header/inner_bg_color');
 $navStretched			= $theme->getCfgDesign('nav/stretched');
 $mainInnerBgColor		= $theme->getCfgDesign('main/inner_bg_color');
 
 $spineColor = $theme->getCfgDesign('spine/spine_color');
 $spineBleed = $theme->getCfgDesign('spine/spine_bleed')?"bleed":"";
 $spineClasses = implode(' ',array($spineColor,$spineBleed));
 
$socialChannels=array();
 
 
$slot_one = $theme->getCfg('spine_social/slot_one');
$slot_two = $theme->getCfg('spine_social/slot_two');
$slot_three = $theme->getCfg('spine_social/slot_three');
$slot_four = $theme->getCfg('spine_social/slot_four');
 
if($slot_one!="skip"){
	 $url = $theme->getCfg('spine_social/slot_one_url');
	 $text = $theme->getCfg('spine_social/slot_one_text');
	 $socialChannels[$slot_one]=array('url'=>$url,'text'=>$text);
}
 
if($slot_two!="skip"){
  	 $url = $theme->getCfg('spine_social/slot_two_url');
	 $text = $theme->getCfg('spine_social/slot_two_text');
	 $socialChannels[$slot_two]=array('url'=>$url,'text'=>$text);
}
if($slot_three!="skip"){
	 $url = $theme->getCfg('spine_social/slot_three_url');
	 $text = $theme->getCfg('spine_social/slot_three_text');
	 $socialChannels[$slot_three]=array('url'=>$url,'text'=>$text);
}
if($slot_four!="skip"){
	 $url = $theme->getCfg('spine_social/slot_four_url');
	 $text = $theme->getCfg('spine_social/slot_four_text');
	 $socialChannels[$slot_four]=array('url'=>$url,'text'=>$text);
}
 
 
 
 /*$socialChannels = array(
					'facebook'=>array('url'=>'http://facebook.com/wsupullman','text'=>'Facebook'),
					'twitter'=>array('url'=>'http://twitter.com/wsupullman','text'=>'Twitter'),
					'youtube'=>array('url'=>'http://www.youtube.com/washingtonstateuniv','text'=>'YouTube'),
					'social'=>array('url'=>'http://social.wsu.edu','text'=>'Social'),
				);*/
 $wsuChannels = array(
					'mywsu-link'=>array('url'=>'https://my.wsu.edu/','text'=>'myWSU'),
					'access-link'=>array('url'=>'http://access.wsu.edu/','text'=>'Access'),
					'policies-link'=>array('url'=>'http://policies.wsu.edu/','text'=>'Policies'),
					'copyright-link'=>array('url'=>'http://copyright.wsu.edu','text'=>'&nbsp;&copy;'),
				);
 if ( !isset($cropping) ) { $cropping = ''; } else { $cropping = ' '.$cropping; }
 
 
$show_search		= $theme->getCfgLayout('spine/show_search');
$show_contact		= $theme->getCfgLayout('spine/show_contact');
$show_share			= $theme->getCfgLayout('spine/show_share');
$show_print			= $theme->getCfgLayout('spine/show_print');
$show_homelink		= $theme->getCfgLayout('spine/show_homelink');
$homelinkText		= $theme->getCfgLayout('spine/homelinkText');
$show_storenetwork	= $theme->getCfgLayout('spine/show_storenetwork');




$homelink="";
if($show_homelink){
	$home_link = Mage::helper('core/url')->getHomeUrl();
	$home_text = ($homelinkText!=="")?$homelinkText:'Store Home';
	$homelink = "<li><a href='{$home_link}'>{$home_text}</a></li>";
}

$searchOps = array();//array('nix-index','nix-site','nix-wsu','nix-facstaff','nix-students');
$searchOptionClasses = implode(' ', $searchOps );

?>
<!-- SPINE -->
<div id="spine" class="spine-column <?=$spineClasses?>">
    <div id="glue" class="spine-glue">
        <header class="spine-header"><a href="<?=$home_link?>" id="wsu-signature">Washington State University</a></header>
        <!-- ACTIONS -->
        <section id="wsu-actions" class="spine-actions">
            <!-- Tabs -->
            <ul id="wsu-actions-tabs" class="spine-actions-tabs clearfix">
				<?php if($show_search): ?><li id="wsu-search-tab" class="spine-search-tab closed" label="Search"><button>Search</button></li><?php endif ?>
				<?php if($show_contact): ?><li id="wsu-contact-tab" class="spine-contact-tab closed" label="Contact"><button>Contact</button></li><?php endif ?>
				<?php if($show_share): ?><li id="wsu-share-tab" class="spine-share-tab closed" label="Share"><button>Share</button></li><?php endif ?>
				<?php if($show_print): ?><li id="wsu-print-tab" class="spine-print-tab closed" label="Print"><button>Print</button></li><?php endif ?>
            </ul>
            <?php if($show_search): ?>
            <!--<section id="wsu-search" class="<?=$searchOptionClasses?> tools closed" data-default="site-search">
                <?php echo $this->getChildHtml('topBar') ?>
            </section>-->
            <?php endif ?>
        </section><!--/#wsu-actions-->
        <section id="spine-navigation" class="spine-navigation">
            <nav class="spine-sitenav <?=(!empty($homelink)?'':'homeless')?>">
                <!-- Your navigation list here
                    • Active link should be denoted with an "active" or "current" link on the link's parent li tag.
                    • First link should be home link (otherwise, add "homeless" class to #site nav)
                    • Replace example navigation list below
                -->
                <ul>
                	<?=$homelink?>
                    <?php //echo $this->getChildHtml('topMenu') ?>
                    <?php $_menu = $this->getLayout()->getBlockSingleton('catalog/navigation')->renderCategoriesMenuHtml(0,'')?>
					<?php if($_menu): ?>
                        <?php echo $_menu ?>
                    <?php endif ?>
                </ul>
            </nav>
            <nav class="spine-offsitenav">
				<ul>
					<li><a href="<?=Mage::getUrl('locations'); ?>">Store Locations</a></li>
					<li><a href="<?=Mage::getUrl('customer-service');?>">Customer Service</a></li>
					<li><a href="<?=Mage::getUrl('privacy');?>">Privacy Policy</a></li>
					<li><a href="<?=Mage::getUrl('catalogsearch/advanced');?>">Advanced Search</a></li>
					<li><a href="<?=Mage::getUrl('order-return');?>">Orders &amp; Returns</a></li>
					<li><a href="https://wsu.edu" target="_blank">WSU Home</a></li>
				</ul>
				<?php // note that the network menu section is missing as this is a standalone site.  Look to the main theme to re-add it ?>
            </nav>
           
        </section><!-- #spine-navigation -->
        <!-- Social and Global Links -->
        <footer class="spine-footer">
            <nav id="wsu-social-channels" class="spine-social-channels">
                <ul>
					<?php foreach($socialChannels as $channel=>$prop) : ?>
						<li class="<?=$channel?>-channel"><a href="<?=(isset($prop['url'])?$prop['url']:'#')?>"><?=(isset($prop['text'])?$prop['text']:'#')?></a></li>
					<?php endforeach;  ?>
                </ul>
            </nav>
            <nav id="wsu-global-links" class="spine-global-links">
                <ul>
					<?php foreach($wsuChannels as $channel=>$prop) : ?>
                        <li class="<?=$channel?>"><a href="<?=(isset($prop['url'])?$prop['url']:'#')?>"><?=(isset($prop['text'])?$prop['text']:'#')?></a></li>
                    <?php endforeach;  ?>
                </ul>
            </nav>        
            <!-- <small class="copyright-link"><a href="http://copyright.wsu.edu">&copy; Washington State University</a></small> -->
        </footer>
    </div><!--/glue-->
</div><!--/spine-->
<!-- /SPINE -->