<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
 
 $store = Mage::app()->getStore();
 $name = $store->getFrontendName();
 
 $theme = $this->helper('wsu_themecontrol');	
 $headerInnerBgColor	= $theme->getCfgDesign('header/inner_bg_color');
 $navStretched			= $theme->getCfgDesign('nav/stretched');
 $mainInnerBgColor		= $theme->getCfgDesign('main/inner_bg_color');
 
 $spineColor = $theme->getCfgDesign('spine/spine_color');
 $spineBleed = $theme->getCfgDesign('spine/spine_bleed')?"bleed":"";
 $spineClasses = implode(' ',array($spineColor,$spineBleed));
 
$socialChannels=array();
 
 
$slot_one = $theme->getCfgGroup('spine_social/slot_one');
$slot_two = $theme->getCfgGroup('spine_social/slot_two');
$slot_three = $theme->getCfgGroup('spine_social/slot_three');
$slot_four = $theme->getCfgGroup('spine_social/slot_four');
 
if($slot_one!="skip"){
	 $url = $theme->getCfgGroup('spine_social/slot_one_url');
	 $text = $theme->getCfgGroup('spine_social/slot_one_text');
	 $socialChannels[$slot_one]=array('url'=>$url,'text'=>$text);
}
 
if($slot_two!="skip"){
  	 $url = $theme->getCfgGroup('spine_social/slot_two_url');
	 $text = $theme->getCfgGroup('spine_social/slot_two_text');
	 $socialChannels[$slot_two]=array('url'=>$url,'text'=>$text);
}
if($slot_three!="skip"){
	 $url = $theme->getCfgGroup('spine_social/slot_three_url');
	 $text = $theme->getCfgGroup('spine_social/slot_three_text');
	 $socialChannels[$slot_three]=array('url'=>$url,'text'=>$text);
}
if($slot_four!="skip"){
	 $url = $theme->getCfgGroup('spine_social/slot_four_url');
	 $text = $theme->getCfgGroup('spine_social/slot_four_text');
	 $socialChannels[$slot_four]=array('url'=>$url,'text'=>$text);
}
 
 
 
 /*$socialChannels = array(
					'facebook'=>array('url'=>'http://facebook.com/wsupullman','text'=>'Facebook'),
					'twitter'=>array('url'=>'http://twitter.com/wsupullman','text'=>'Twitter'),
					'youtube'=>array('url'=>'http://www.youtube.com/washingtonstateuniv','text'=>'YouTube'),
					'social'=>array('url'=>'http://social.wsu.edu','text'=>'Social'),
				);*/
 $wsuChannels = array(
					'mywsu'=>array('url'=>'https://my.wsu.edu/','text'=>'myWSU'),
					'access'=>array('url'=>'http://access.wsu.edu/','text'=>'Access'),
					'policies'=>array('url'=>'http://policies.wsu.edu/','text'=>'Policies'),
					'copyright'=>array('url'=>'http://copyright.wsu.edu','text'=>'&nbsp;&copy;'),
				);
 if ( !isset($cropping) ) { $cropping = ''; } else { $cropping = ' '.$cropping; }
 
 
$show_search		= $theme->getCfgLayout('spine/show_search');
$show_contact		= $theme->getCfgLayout('spine/show_contact');
$show_share			= $theme->getCfgLayout('spine/show_share');
$show_print			= $theme->getCfgLayout('spine/show_print');
$show_homelink		= $theme->getCfgLayout('spine/show_homelink');
$homelinkText		= $theme->getCfgLayout('spine/homelinkText');
$show_storenetwork	= $theme->getCfgLayout('spine/show_storenetwork');




$homelink="";
if($show_homelink){
	$home_link = Mage::helper('core/url')->getHomeUrl();
	$home_text = ($homelinkText!=="")?$homelinkText:'Store Home';
	$homelink = "<li><a href='{$home_link}'>{$home_text}</a></li>";
}

$searchOps = array();//array('nix-index','nix-site','nix-wsu','nix-facstaff','nix-students');
$searchOptionClasses = implode(' ', $searchOps );

?>
<!-- SPINE -->
<div id="spine" class="spine-column <?=$spineClasses?>">
    <div id="glue" class="spine-glue">
        <header class="spine-header"><a href="http://www.wsu.edu/" id="wsu-signature">Washington State University</a></header>
        <!-- ACTIONS -->
        <section id="wsu-actions" class="spine-actions">
            <!-- Tabs -->
            <ul id="wsu-actions-tabs" class="spine-actions-tabs clearfix">
				<?php if($show_search): ?><li id="wsu-search-tab" class="spine-search-tab closed" label="Search"><button>Search</button></li><?php endif ?>
				<?php if($show_contact): ?><li id="wsu-contact-tab" class="spine-contact-tab closed" label="Contact"><button>Contact</button></li><?php endif ?>
				<?php if($show_share): ?><li id="wsu-share-tab" class="spine-share-tab closed" label="Share"><button>Share</button></li><?php endif ?>
				<?php if($show_print): ?><li id="wsu-print-tab" class="spine-print-tab closed" label="Print"><button>Print</button></li><?php endif ?>
            </ul>
            <?php if($show_search): ?>
            <section id="wsu-search" class="<?=$searchOptionClasses?> tools closed" data-default="site-search">
                <?php echo $this->getChildHtml('topBar') ?>
            </section>
            <?php endif ?>
        </section><!--/#wsu-actions-->
        <section id="spine-navigation" class="spine-navigation">
            <nav class="spine-sitenav <?=(!empty($homelink)?'':'homeless')?>">
                <!-- Your navigation list here
                    • Active link should be denoted with an "active" or "current" link on the link's parent li tag.
                    • First link should be home link (otherwise, add "homeless" class to #site nav)
                    • Replace example navigation list below
                -->
                <ul>
                	<?=$homelink?>
                    <?php //echo $this->getChildHtml('topMenu') ?>
                    <?php $_menu = $this->getLayout()->getBlockSingleton('catalog/navigation')->renderCategoriesMenuHtml(0,'')?>
					<?php if($_menu): ?>
                        <?php echo $_menu ?>
                    <?php endif ?>
                </ul>
            </nav>
            
            <?php if($show_storenetwork): ?>
            <nav class="spine-offsitenav">
                <ul>
                
                <?php 
					$currentUrl = Mage::helper('core/url')->getCurrentUrl();
					$currentUrl = str_ireplace('www.', '', parse_url($currentUrl, PHP_URL_HOST));
					
					$websites = Mage::getModel('core/website')->getCollection();
					$sessionId = Mage::getSingleton("core/session")->getEncryptedSessionId(); 
					if(count($websites)>5):?>
                
                        <li><select id="website-changer" onChange="document.location=this.options[selectedIndex].value">
                                <option selected="selected">Switch stores</option>
                            <?php
                            foreach($websites as $website) {
                                $default_store = $website->getDefaultStore();
                                $url_obj = new Mage_Core_Model_Url();
                                $default_store_path = $url_obj->getBaseUrl(array('_store'=> $default_store->getCode()));
                            ?>
                                <!--<option <?php if(strstr($default_store_path,$currentUrl )>-1):?>selected="selected"<?php endif; ?> value="<?php echo $default_store_path."?SID=".$sessionId ?>"  data-default_store_path="<?=$default_store_path ?>" data-currentUrl="<?=$currentUrl ?>"><?php echo $website->getName()?></option>-->
                                <option value="<?php echo $default_store_path."?SID=".$sessionId ?>"  data-default_store_path="<?=$default_store_path ?>" data-currentUrl="<?=$currentUrl ?>">
                                    <?php echo $website->getName()?>
                                </option>
                            <?php
                            }
                            ?>
                            </select>
                        </li>
                    <?php else: ?>
<?php
                        foreach($websites as $website) {
                            $default_store = $website->getDefaultStore();
							if(!empty($default_store)){
								$url_obj = new Mage_Core_Model_Url();
								$default_store_path = $url_obj->getBaseUrl(array('_store'=> $default_store->getCode()));
							?>
						<li><a href="<?php echo $default_store_path."../../../../foundation.store.wsu.edu/page/html/?SID=".$sessionId ?>"><?php echo $website->getName()?></a></li>
							<?php
							}
                        }
                        ?>
                    <?php endif; ?>
                </ul>
            </nav>
            <?php endif; ?>
        </section><!-- #spine-navigation -->
        <!-- Social and Global Links -->
        <footer class="spine-footer">
            <nav id="wsu-social-channels" class="spine-social-channels">
                <ul>
					<?php foreach($socialChannels as $channel=>$prop) : ?>
						<li class="<?=$channel?>-channel"><a href="<?=(isset($prop['url'])?$prop['url']:'#')?>"><?=(isset($prop['text'])?$prop['text']:'#')?></a></li>
					<?php endforeach;  ?>
                </ul>
            </nav>
            <nav id="wsu-global-links" class="spine-global-links">
                <ul>
					<?php foreach($wsuChannels as $channel=>$prop) : ?>
                        <li id="<?=$channel?>"><a href="<?=(isset($prop['url'])?$prop['url']:'#')?>"><?=(isset($prop['text'])?$prop['text']:'#')?></a></li>
                    <?php endforeach;  ?>
                </ul>
            </nav>        
            <!-- <small class="copyright-link"><a href="http://copyright.wsu.edu">&copy; Washington State University</a></small> -->
        </footer>
    </div><!--/glue-->
</div><!--/spine-->
<!-- /SPINE -->