<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
/**
 * - Removed top "checkout" button
 * - Added table wrapper (to show background image)
 * - Changed "continue shopping" button and "update cart" button
 * - Added class 'last' in table header last cells
 * - Rearranged layout of 'cart-collaterals'
 */
?>
<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Cart') ?></h1><br/>
		<h3><?php echo $this->__('Please review your cart and proceed to checkout') ?></h3>
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" class="the-cart-form padded narrow">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
        <div class="cart-table-wrapper">
            <table id="shopping-cart-table" class="data-table cart-table">
                <col class="col-img" width="1" />
                <col />
                <col class="col-edit" width="1" />
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                <col class="col-wish" width="1" />
            <?php endif ?>
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col class="col-unit-price" width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col class="col-unit-price" width="1" />
            <?php endif; ?>
                <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col class="<?php if($this->helper('tax')->displayCartBothPrices()) echo 'col-total-excl'; else echo 'col-total'; ?>" width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col class="<?php if($this->helper('tax')->displayCartBothPrices()) echo 'col-total-incl'; else echo 'col-total'; ?>" width="1" />
            <?php endif; ?>
                <col class="col-delete" width="1" />

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th class="col-img" rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Name') ?></span></th>
                        <!--<th class="col-edit" rowspan="<?php echo $mergedCells; ?>"></th>-->
                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th class="col-wish a-center" rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                        <?php endif ?>
                        <th class="col-unit-price a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                        <th class="col-delete a-center" rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="col-unit-price a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th class="col-unit-price"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="col-total-excl a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th class="col-total-incl"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                    <?php endif; ?>
                </thead>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
			<div id="cart_function_area">
				<?php if($this->getContinueShoppingUrl()): ?>
					<button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue btn-inline" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><?php echo $this->__('Continue Shopping') ?></span></button>
				<?php endif; ?>
					<button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update btn-inline"><span><?php echo $this->__('Update Shopping Cart'); ?></span></button>
	
				<?php /*?>
				<a id="link-cart-update" href="#">Test submit</a>
				<script type="text/javascript">
				jQuery(function($){
					$('#link-cart-update').click(function() {
						$('.the-cart-form').submit();
					});
				});
				</script>
				<?php */?>
				
				<?php /*?>
				<button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
				<!--[if lt IE 8]>
				<input type="hidden" id="update_cart_action_container" />
				<script type="text/javascript">
				//<![CDATA[
					Event.observe(window, 'load', function()
					{
						// Internet Explorer (lt 8) does not support value attribute in button elements
						$emptyCartButton = $('empty_cart_button');
						$cartActionContainer = $('update_cart_action_container');
						if ($emptyCartButton && $cartActionContainer) {
							Event.observe($emptyCartButton, 'click', function()
							{
								$emptyCartButton.setAttribute('name', 'update_cart_action_temp');
								$cartActionContainer.setAttribute('name', 'update_cart_action');
								$cartActionContainer.setValue('empty_cart');
							});
						}
	
					});
				//]]>
				</script>
				<![endif]-->
				<?php */?>
			</div>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        <!-- end: cart-table-wrapper -->
        </fieldset>
    </form>
    <div class="cart-collaterals nested-container">

        <div class="column">
        	<?php if ($tmpHtml = $this->getChildHtml('checkout.cart.extra')): ?>
            <div class="checkout_cart_extra">
                <?php /* Extensions placeholder */ ?>
                <?php echo $tmpHtml; ?>
			</div>
            <?php endif; ?>
            
            <?php if ($tmpHtml = $this->getChildHtml('block_cart_below_table')): ?>
            	<div class="block_cart_below_table"><?php echo $tmpHtml; ?></div>
            <?php endif; ?>
            
			<?php if (!$this->getIsVirtual() && $tmpHtml = $this->getChildHtml('shipping')): ?>
			<div class="shipping">
            	<?php echo $tmpHtml; ?>
			</div>
			<?php endif; ?>
			 <?php if ($tmpHtml = $this->getChildHtml('coupon') ): ?>
			<div class="coupon">
            	<?php echo $tmpHtml ?>
            </div>
			<?php endif; ?>
			<?php if ($tmpHtml = $this->getChildHtml('crosssell') ): ?>
            <div class="crosssell">
                <?php echo $tmpHtml ?>
            </div>
			<?php endif; ?>
        </div> <!-- end: cart-left-column -->
    	<div class="column">
            <div class="totals grid-full alpha omega">
                <div class="totals-inner">
                <?php echo $this->getChildHtml('totals'); ?>
                <?php if(!$this->hasError()): ?>
                    <ul class="checkout-types">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                    	<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    		<li><?php echo $methodHtml; ?></li>
                    	<?php endif; ?>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                </div>
            </div>
			<?php if ($tmpHtml = $this->getChildHtml('block_cart_below_totals')): ?>
            	<div class="block_cart_below_totals grid-full alpha omega"><?php echo $tmpHtml; ?></div>
            <?php endif; ?>
        </div> <!-- end: cart-right-column -->
    </div>
</div>
