<div id="banner_area">
	<div id="homepage_banners" class="cycle-slideshow"
		data-cycle-fx="scrollHorz"
		data-cycle-pause-on-hover="true"
    	data-cycle-speed="200"
		data-cycle-pager="#banner-pager"
		>
		<img src="/media/store-media/connections.store.wsu.edu/homepage-banners/1.jpg" />
		<img src="/media/store-media/connections.store.wsu.edu/homepage-banners/2.jpg" />
		<img src="/media/store-media/connections.store.wsu.edu/homepage-banners/3.jpg" />
		<img src="/media/store-media/connections.store.wsu.edu/homepage-banners/4.jpg" />
	</div>
	
	<div id="banner-pager"></div>
</div>
<div id="home_page_cats">
	<ul class="row quarters pad narrow">
		<li class="column one">
			<a href=""><img src="/media/store-media/connections.store.wsu.edu/home-page-cats/1.jpg" /></a>
		</li>
		<li class="column two">
			<a href=""><img src="/media/store-media/connections.store.wsu.edu/home-page-cats/2.jpg" /></a>
		</li>
		<li class="column three">
			<a href=""><img src="/media/store-media/connections.store.wsu.edu/home-page-cats/3.jpg" /></a>
		</li>
		<li class="column four">
			<a href=""><img src="/media/store-media/connections.store.wsu.edu/home-page-cats/4.jpg" /></a>
		</li>
	</ul>
</div>