<script>
jQuery(document).ready(function(){
	jQuery(window).on("resize",function(){
		jQuery("#home-holder").css("font-size",function(){
		   return (jQuery("#home-holder").width() * 0.00825); //we know the max from the main width but we hard coded the ratio value
		});
	 }).trigger("resize");
});
</script>
<div style="height: 0px; padding-top: 66.7755%; width: 100%; position: relative; font-size: 6.2205px; color: rgb(236, 236, 236); background: url(&quot;/media/store-media/connections.store.wsu.edu/homepage/grand-open-bk.jpg&quot;) 0% 0% / contain no-repeat rgb(148, 30, 61);" id="home-holder">

  <div style="background: rgba(123,159,234,0.15); position:absolute; top:0px; left:0px;width: 100%;height: 100%;display: flex;flex-flow: column wrap;justify-content: flex-start;align-content: center;text-align:center;">
  	<div style="
    margin-top: 3.6em;
    margin-bottom: 3.4em;
"><h2 style="border-bottom:2px solid #ececec; color:#ececec;font-size: 2.5em;display: inline-block;">Grand (re)Opening Sale</h2></div>
  	<div style="font-size:19em;display: block;font-weight: 700;line-height: 0.8em;/* margin-top: 1em; */text-align: left;color:#ececec;padding-left: 0.2em;">YOUR new</div>
	<div style="font-size: 7.254em;display: block;color:#ececec;font-weight: 600;text-align: right;padding-right: 1em;line-height: 1em;">Store for everything WSU</div>
	<div><a href="#" style="font-size:2.2em;display: inline-block; background:#ececec; color:#171717;padding: 0.5em 1.5em;font-weight: 700;width: auto;margin-top: 2.3em;">Shop All Sale Items</a></div>
    
    <div style="display:flex;flex-flow: row wrap;align-content: center;justify-content: center; text-align:center;margin-top: 3em;">
		<a href="#" style="font-size:3em;color:#ececec;font-weight:600;margin-right:4.2em;">Shop men's</a>
		<a href="#" style="font-size:3em;color:#ececec;font-weight:600;margin-right:4.2em;">Shop women's</a>
		<a href="#" style="font-size:3em;color:#ececec;font-weight:600;/* margin-right:4.2em; */">Shop kid's</a>
	 </div>
	 <p style="font-size: 2.2em;line-height: 1.2em;margin-top: 1.2em;">Shop early for the best selection. Quantities limited. <br>
Discount based on original prices.</p>
  
		<h3 style="font-size:3.09em;font-weight:800; text-align:center; text-transform:capitalize;">Hot Items</h3>
		<div style="display:flex;flex-flow: row wrap;align-content: center; border-top:2px #ececec solid; text-align:center;justify-content: center;padding-top: 1.5em;">
			<a href="#" style="color:#ececec;font-size:1.8em;margin-right: 1em;"><img style="width:3.3em;height:3.3em;float:left;margin-right:5px;background:#ececec;"> Title stuff said here</a>
			<a href="#" style="color:#ececec;font-size:1.8em;margin-right: 1em;"><img style="width:3.3em;height:3.3em;float:left;margin-right:5px;background:#ececec;"> Title stuff said here</a>
			<a href="#" style="color:#ececec;font-size:1.8em;"><img style="width:3.3em;height:3.3em;float:left;margin-right:5px;background:#ececec;"> Title stuff said here</a>
		</div>
  </div>

  

</div>