<div id="banner_area">
	<div id="homepage_banners" class="cycle-slideshow"
		data-cycle-fx="scrollHorz"
		data-cycle-pause-on-hover="true"
    	data-cycle-speed="200"
		data-cycle-pager="#banner-pager"
		data-cycle-slides="> a"
		>
		<a href=""><img src="/media/store-media/connections.store.wsu.edu/homepage-banners/1.jpg" /></a>
		<a href=""><img src="/media/store-media/connections.store.wsu.edu/homepage-banners/2.jpg" /></a>
		<a href=""><img src="/media/store-media/connections.store.wsu.edu/homepage-banners/3.jpg" /></a>
		<a href=""><img src="/media/store-media/connections.store.wsu.edu/homepage-banners/4.jpg" /></a>
	</div>
	<div id="banner-pager"></div>
</div>
<div id="home_page_cats">
	<ul class="row quarters pad narrow">
		<li class="column one">
        	<h3>Come visit the store!</h3>
            <p>We are excited to announce that butch will be in the store 11/1/15</p>
			<!--<a href=""><img src="/media/store-media/connections.store.wsu.edu/home-page-cats/1.jpg" /></a>-->
		</li>
		<li class="column two">
        	<h3>Nothing Compares!</h3>
            <p>Coug Cheese, nothing compares</p>
			<!--<a href=""><img src="/media/store-media/connections.store.wsu.edu/home-page-cats/2.jpg" /></a>-->
		</li>
		<li class="column three">
        	<h3>Wine?!</h3>
            <p>We sell only the best!</p>
			<!--<a href=""><img src="/media/store-media/connections.store.wsu.edu/home-page-cats/3.jpg" /></a>-->
		</li>
		<li class="column four">
        	<h3>Why Not</h3>
            <p>This is where it's at</p>
			<!--<a href=""><img src="/media/store-media/connections.store.wsu.edu/home-page-cats/4.jpg" /></a>-->
		</li>
	</ul>
</div>