<nav class="spine-offsitenav custom">
	<ul>
		<li><a href="<?=Mage::getUrl('locations'); ?>">Store Locations</a></li>
		<li><a href="<?=Mage::getUrl('customer-service');?>">Customer Service</a></li>
		<li><a href="<?=Mage::getUrl('privacy');?>">Privacy Policy</a></li>
		<li><a href="<?=Mage::getUrl('catalogsearch/advanced');?>">Advanced Search</a></li>
		<li><a href="<?=Mage::getUrl('order-return');?>">Orders &amp; Returns</a></li>
		<li><a href="https://wsu.edu" target="_blank">WSU Home</a></li>
	</ul>
	<?php // note that the network menu section is missing as this is a standalone site.  Look to the main theme to re-add it ?>
</nav>