<?php
$helper = $this->helper('wsu_opc');
$predone_billing = $this->escapeHtml($this->getAddress()->getStreet(1));
?>
<div id="co-billing-form">
    <?php if("" !== $predone_billing): ?>
        <a id="billing_click_to_save" class="to_save saved hide"></a>
    <?php endif;?>
    <h3><?=$this->__('Billing Information')?></h3>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
        <li class="wide">
            <label for="billing-address-select" class="notice"><?=$this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box">
                <?=$this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <fieldset>
            <input type="hidden" name="billing[address_id]" value="<?=$this->getAddress()->getId() ?>" id="billing:address_id" />
            <ul>
                <li class="fields">
					<?=$this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
				</li>
				<?php if(Mage::getStoreConfig('customer/extras/show_company')): ?>
                <li class="fields">
                    <div class="field">
                        <label for="billing:company"><?=$this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:company" name="billing[company]" value="<?=$this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?=$this->__('Company') ?>" class="input-text <?=$helper->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
				</li>
				<?php endif; ?>
					 
				<?php if(!$this->isCustomerLoggedIn()): ?>
				<li class="fields">
                    <div class="field">
                        <label for="billing:email" class="required"><em>*</em><?=$this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" value="<?=$this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?=$this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </div>
                </li>
				<?php endif; ?>
        		<?php $_streetValidationClass = $helper->getAttributeValidationClass('street') . " validate-for-pobox "; ?>
                <li class="wide">
                    <label for="billing:street1" class="required"><em>*</em><?=$this->__('Address') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?=$this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?=$this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?=$_streetValidationClass ?> shipping_method_value" />
                    </div>
                </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" title="<?=$this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?=$_i ?>" value="<?=$this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?=$_streetValidationClass ?> shipping_method_value" />
                    </div>
                </li>
        <?php endfor; ?>
                <?php if ($helper->isVatAttributeVisible()) : ?>
                <li class="wide">
                    <label for="billing:vat_id"><?=$this->__('VAT Number') ?></label>
                    <div class="input-box">
                        <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?=$this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?=$this->__('VAT Number') ?>" class="input-text <?=$helper->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                </li>
                <?php endif; ?>
                <li class="fields">
                    <div class="field">
                        <label for="billing:city" class="required"><em>*</em><?=$this->__('City') ?></label>
                        <div class="input-box">
							<input type="text" title="<?=$this->__('City') ?>" name="billing[city]" value="<?=$this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?=$helper->getAttributeValidationClass('city') ?> shipping_method_value" id="billing:city" />
                        </div>
                    </div>
                    <div class="field">
						<label for="billing:region_id" class="required"><em>*</em><?=$this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?=$this->__('State/Province') ?>" class="validate-select shipping_method_value" style="display:none;">
                                <option value=""><?=$this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?=$this->getAddress()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]" value="<?=$this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?=$this->__('State/Province') ?>" class="input-text <?=$helper->getAttributeValidationClass('region') ?> shipping_method_value" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:postcode" class="required"><em>*</em><?=$this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?=$this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?=$this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip <?=$helper->getAttributeValidationClass('postcode') ?> shipping_method_value" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:country_id" class="required"><em>*</em><?=$this->__('Country') ?></label>
                        <div class="input-box">
                            <?=$this->getCountryHtmlSelect('billing') ?>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:telephone" class="required"><em>*</em><?=$this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?=$this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?=$this->__('Telephone') ?>" class="input-text validate-phoneLax <?=$helper->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:fax"><?=$this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[fax]" value="<?=$this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?=$this->__('Fax') ?>" class="input-text <?=$helper->getAttributeValidationClass('fax') ?>" id="billing:fax" />
                        </div>
                    </div>
                </li>
                <?php if(!$this->isCustomerLoggedIn()): ?>

                    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                            <li class="fields">
                            <?php if ($_dob->isEnabled()): ?>
                                <div class="field">
                                    <?=$_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($_gender->isEnabled()): ?>
                                <div class="field">
                                    <?=$_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                </div>
                            <?php endif ?>
                            </li>
                        <?php endif ?>

                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                            <li>
                                <?=$_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </li>
                    <?php endif ?>

                    
                <?php endif; ?>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                	<div class="clear"></div>
                    <li class="control">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?=$this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?=$this->__('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
                <?=$this->getChildHtml('form.additional.info'); ?>
            </ul>
        </fieldset>
    </li>
    <?php /* Extensions placeholder */ ?>
    <?=$this->getChildHtml('checkout.onepage.billing.extra')?>
    <?php if(!$this->isCustomerLoggedIn()): ?>
    
    	<?php
    	$guest_allowed = $this->getQuote()->isAllowedGuestCheckout();
    	if($guest_allowed): ?>
	    <li class="control">
	            <input type="checkbox" name="billing[create_account]" id="billing:create_account" value="1" title="<?=$this->__('Create an account for later use') ?>"  class="checkbox" /><label for="billing:create_account"><?=$this->__('Create an account for later use') ?></label>
	    </li>
	    <?php else:?>
	    	<input type="hidden" name="billing[create_account]" id="billing:create_account" value="1" />
	    <?php endif;?>
        
		<li class="fields <?php if($guest_allowed):?>hidden<?php endif;?>" id="register-customer-password">
			<div class="field">
				<label for="billing:customer_password" class="required"><em>*</em><?=$this->__('Password') ?></label>
				<div class="input-box">
					<input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?=$this->__('Password') ?>" class="input-text validate-password <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off"/>
				</div>
			</div>
			<div class="field">
				<label for="billing:confirm_password" class="required"><em>*</em><?=$this->__('Confirm Password') ?></label>
				<div class="input-box">
					<input type="password" name="billing[confirm_password]" title="<?=$this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text validate-cpassword <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off"/>
				</div>
			</div>
            <p>If you have a downloadable product, you will not be able to check out as a guest.  Please set a password, or login.</p>
		</li>
		<div class="clear"></div>
    
    <?php endif;?>
    
    <?php if ($this->canShip()): ?>
        <li class="control <?php if (!Mage::helper('wsu_opc')->isShowShippingForm()):?>hidden<?php endif;?>">
            <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?=$this->__('Ship to this address') ?>" class="checkbox   " /><label for="billing:use_for_shipping_yes"><?=$this->__('Use Billing address to ship to.') ?></label>
        </li>
    <?php endif; ?>
    </ul>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>

</div>
<script type="text/javascript">
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?=$this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
//]]>
</script>
