<?php
$cp_id = $this->getCouponCode();
/*  was thinkin maybe a time that the code would change the shipping... but the discount is apply to the cart .. so maybe not.. well come back to 
if(strlen($cp_id)){
	$oCoupon = Mage::getModel('salesrule/coupon')->load($cp_id, 'code');
	$oRule = Mage::getModel('salesrule/rule')->load($oCoupon->getRuleId());
	var_dump($oRule->getData());
}
*/
$loading = '<div class="opc-ajax-loader" style="display:none;"><div class="loader"><div class="outer"></div><div class="inner"></div></div></div>';
?>

    <div class="discount">
        <div class="discount-form">
            <label for="coupon_code"><?=$this->__('Enter your coupon code:') ?></label>            
            <div class="input-box">
                <input class="input-text" id="coupon_code" type="text" name="coupon_code" value="<?=$this->htmlEscape($cp_id) ?>" autocomplete="off"/>
            </div>
            <div class="buttons-set">
                <button type="button" title="<?=$this->__('Apply') ?>" class="button apply-coupon"  value="<?=$this->__('Apply') ?>"><span><span><?=$this->__('Apply') ?></span></span></button>
                <?php if(strlen($cp_id)): ?>
                    &nbsp; <button type="button" title="<?=$this->__('Cancel') ?>" class="button remove-coupon right"  value="<?=$this->__('Cancel') ?>"><span><span><?=$this->__('Cancel') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
    <div class="discount" >
        <h2><span><?php echo $this->__('Alumni Save 10%!!') ?></span></h2>
        <div class="discount-form">
            
            <p style="    padding-bottom: 0px;"><img src="/media/store-media/connections.store.wsu.edu/skin/alumni-cards.png" style="float:right;max-width:150px; width:auto;" /><?php echo $this->__('All card-carrying WSU alumni can save at the Connections Store.  ') ?></p>
            <input type="hidden" name="remove" id="alumni_remove-coupone" value="0" />
            <div class="input-box">
                <input type="number" class="input-text" id="alumni_coupon_code"  value="" />
                
             <input type="hidden" name="coupon_code" id="alumni_real" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />   

            </div>
            <div class="buttons-set">
                
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove Discount')) ?>" class="button" onclick="alumni_discountForm.submit(true)" value="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove Discount')) ?>"><span><span><?php echo $this->__('Remove  Number') ?></span></span></button>
                 <?php else:?>  
                 <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Apply Discount')) ?>" class="button" onclick="alumni_discountForm.submit(false)" value="<?php echo Mage::helper('core')->quoteEscape($this->__('Apply Discount')) ?>"><span><span><?php echo $this->__('Submit Number') ?></span></span></button> 
                <?php endif;?>
            </div>
            <p style="font-size: 0.8em;"><?php echo $this->__('* discount does not include wine, cheese and sale items.') ?></p>
        </div>
    </div>
    
    
<?=$loading?>