<?php
    $helper = $this->helper('wsu_opc');
    $predone_billing = $this->escapeHtml($this->getAddress()->getStreet(1));
?>


    <?php if(""!==$predone_billing): ?>
        <a id="shipping_click_to_save" class="to_save saved hide"></a>
    <?php endif;?>
<div class="">	

	<h3><?=$this->__('Shipping Address')?></h3>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
       <li class="wide">
           <label for="shipping-address-select" class="notice"><?=$this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box">
               <?=$this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </li>
    <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?=$this->getAddress()->getId() ?>" id="shipping:address_id" />
                <ul>
                    <li class="fields"><?=$this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?></li>
                    <li class="fields">
                        <div class="fields">
                            <label for="shipping:company"><?=$this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" id="shipping:company" name="shipping[company]" value="<?=$this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?=$this->__('Company') ?>" class="input-text <?=$helper->getAttributeValidationClass('company') ?>"/>
                            </div>
                        </div>
                    </li>
            
        		<?php $_streetValidationClass = $helper->getAttributeValidationClass('street') . " validate-pobox "; ?>
                    <li class="wide">
                        <label for="shipping:street1" class="required"><em>*</em><?=$this->__('Address') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?=$this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?=$this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?=$_streetValidationClass ?> shipping_method_value" />
                        </div>
                    </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide">
                        <div class="input-box">
                            <input type="text" title="<?=$this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?=$_i ?>" value="<?=$this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?=$_streetValidationClass ?> shipping_method_value" />
                        </div>
                    </li>
            <?php endfor; ?>
                    <?php if ($helper->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="billing:vat_id"><?=$this->__('VAT Number'); ?></label>
                        <div class="input-box">
                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?=$this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?=$this->__('VAT Number'); ?>" class="input-text <?=$helper->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:city" class="required"><em>*</em><?=$this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?=$this->__('City') ?>" name="shipping[city]" value="<?=$this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?=$helper->getAttributeValidationClass('city') ?> shipping_method_value" id="shipping:city" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:region" class="required"><em>*</em><?=$this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?=$this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?=$this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?=$this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?=$this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?=$this->__('State/Province') ?>" class="input-text <?=$helper->getAttributeValidationClass('region') ?> shipping_method_value" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:postcode" class="required"><em>*</em><?=$this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?=$this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?=$this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip <?=$helper->getAttributeValidationClass('postcode') ?> shipping_method_value"  />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:country_id" class="required"><em>*</em><?=$this->__('Country') ?></label>
                            <div class="input-box">
                                <?=$this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:telephone" class="required"><em>*</em><?=$this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[telephone]" value="<?=$this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?=$this->__('Telephone') ?>" class="input-text <?=$helper->getAttributeValidationClass('telephone') ?> validate-phoneStrict" id="shipping:telephone" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:fax"><?=$this->__('Fax') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[fax]" value="<?=$this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?=$this->__('Fax') ?>" class="input-text <?=$helper->getAttributeValidationClass('fax') ?>" id="shipping:fax"  />
                            </div>
                        </div>
                    </li>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                	<div class="clear"></div>
                    <li class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?=$this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?=$this->__('Save in address book') ?></label></li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
                </ul>
            </fieldset>
        </li>
        <li class="control hidden">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?=$this->__('Use Billing Address') ?>" class="checkbox" /><label for="shipping:same_as_billing"><?=$this->__('Use Billing Address') ?></label>
        </li>
    </ul>

<script type="text/javascript">
//<![CDATA[
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?=$this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>
</div>